# _config.yml
title: "IT 304 FINAL PROJECT"
description: "The course explores societal issues tied to advanced IT. For the final project, students will choose a tech like ChatGPT or voice recognition, explore real-world uses via articles/papers, analyze its impact using two ethical lenses, and present findings on a visually clear, GitHub-hosted website."
theme: jekyll-theme-modernist 
